// Compatibility regression checks generated by ChatGPT.
#include "Sample.h"
#include "ChannelHandler.h"
#include "Midi.h"
#include "RiffWav.h"
#include <cassert>
#include <cstring>
using namespace spiralcore;

class CountingAllocator : public MallocAllocator {
public:
    CountingAllocator() : allocations(0), releases(0) {}
    char *New(unsigned int size) { ++allocations; return MallocAllocator::New(size); }
    void Delete(char *p) { ++releases; MallocAllocator::Delete(p); }
    int allocations, releases;
};

int main() {
#ifndef USE_LIBSNDFILE
    assert(sizeof(CanonicalWavHeader) == 36);
    assert(sizeof(DataHeader) == 8);
#endif
    Allocator *original=Sample::GetAllocator();
    CountingAllocator allocator;
    Sample::SetAllocator(&allocator);
    {
        Sample s(16), copy;
        assert(s.IsEmpty());
        s.Set(2.0f);
        s.SetDataGranularity(4);
        s.GetRegion(copy,0,7);
        assert(copy.GetLength()==4 && copy[0]==2.0f);
        assert(!s.IsEmpty());
        copy=s;
        copy=copy;
        assert(copy.GetLength()==16 && copy[0]==2.0f && !copy.IsEmpty());
        int metadata=1;
        s.setSpecificData(&metadata);
        s.setSampleType(Sample::MIDI);
        assert(s.getSpecificData()==&metadata && s.getSampleType()==Sample::MIDI);
        s.Zero();
        assert(s.IsEmpty() && s[0]==0.0f);
    }
    assert(allocator.allocations==allocator.releases);
    Sample::SetAllocator(original);

    ChannelHandler channels;
    int input=1, output=2, replacement=7;
    channels.Register("input",&input);
    channels.Register("output",&output,ChannelHandler::OUTPUT);
    channels.FlushChannels();
    channels.Set("input",5);
    channels.UpdateDataNow();
    assert(input==5 && channels.GetInt("output")==2);
    channels.ReplaceData("output",&replacement,sizeof(replacement));
    assert(channels.GetInt("output")==7);
    char text[4096]={0};
    void *ptr=0;
    channels.RegisterString("text",text);
    channels.Register("ptr",&ptr);
    channels.SetString("text","library and SSM");
    channels.SetPtr("ptr",&replacement);
    channels.UpdateDataNow();
    assert(std::strcmp(text,"library and SSM")==0 && ptr==&replacement);
    MidiEvent event(MidiEvent::ON,60,100);
    assert(event.GetNote()==60 && event.GetVolume()==100);
}
